# Generated by Django 4.2.9 on 2026-04-29 17:44

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#10B981', max_length=7, verbose_name='Couleur hex')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('extrait', models.TextField(max_length=500, verbose_name='Extrait / Introduction')),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(config_name='default', verbose_name='Contenu')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image principale')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('en_vedette', models.BooleanField(default=False, verbose_name='En vedette')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('meta_titre', models.CharField(blank=True, max_length=70, verbose_name='Meta titre (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description (SEO)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categorie')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
