# Generated by Django 4.2.9 on 2026-04-29 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmakers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Compétition')),
                ('slug', models.SlugField(unique=True)),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitions/')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compétition',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_domicile', models.CharField(max_length=200, verbose_name='Équipe domicile')),
                ('equipe_exterieur', models.CharField(max_length=200, verbose_name='Équipe extérieur')),
                ('date_match', models.DateTimeField(verbose_name='Date et heure')),
                ('score_domicile', models.PositiveIntegerField(blank=True, null=True)),
                ('score_exterieur', models.PositiveIntegerField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False, verbose_name='Terminé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='pronostics.competition')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-date_match'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Sport')),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='football', max_length=50, verbose_name='Icone SVG')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pronostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du pronostic')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('prediction', models.CharField(max_length=200, verbose_name='Prédiction (ex: 1, X, 2, BTTS)')),
                ('cote', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cote')),
                ('mise_recommandee', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Mise recommandée (%)')),
                ('analyse', models.TextField(verbose_name='Analyse détaillée')),
                ('confiance', models.IntegerField(choices=[(1, '1/5 ⭐'), (2, '2/5 ⭐'), (3, '3/5 ⭐'), (4, '4/5 ⭐'), (5, '5/5 ⭐')], default=3, verbose_name='Confiance')),
                ('resultat', models.CharField(choices=[('pending', 'En attente'), ('win', 'Gagné'), ('loss', 'Perdu'), ('void', 'Remboursé')], default='pending', max_length=10)),
                ('est_vip', models.BooleanField(default=False, verbose_name='Réservé VIP')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronostics', to=settings.AUTH_USER_MODEL)),
                ('bookmaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronostics', to='bookmakers.bookmaker')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronostics', to='pronostics.match')),
            ],
            options={
                'verbose_name': 'Pronostic',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='pronostics.sport'),
        ),
        migrations.CreateModel(
            name='CommentairePronostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000, verbose_name='Commentaire')),
                ('approuve', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pronostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='pronostics.pronostic')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['-created_at'],
            },
        ),
    ]
