# Generated by Django 4.2.9 on 2026-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronostic',
            name='resultat',
            field=models.CharField(choices=[('pending', '⏳ En attente'), ('win', 'Gagné'), ('loss', 'Perdu'), ('void', 'Remboursé')], default='pending', max_length=10),
        ),
    ]
