# Generated by Django 4.2.9 on 2026-04-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('slug', models.SlugField(unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix (FCFA)')),
                ('duree_jours', models.PositiveIntegerField(verbose_name='Durée (jours)')),
                ('description', models.TextField(blank=True)),
                ('fonctionnalites', models.JSONField(default=list, verbose_name='Liste des fonctionnalités')),
                ('populaire', models.BooleanField(default=False, verbose_name='Plan populaire')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=10)),
                ('methode_paiement', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Carte bancaire'), ('crypto', 'Crypto')], default='momo', max_length=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_paiement', models.CharField(blank=True, max_length=200, verbose_name='Référence paiement')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vip.planabonnement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'ordering': ['-date_debut'],
            },
        ),
    ]
