# Generated by Django 4.2.9 on 2026-04-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Bookmaker')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bookmakers/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lien_affilie', models.URLField(verbose_name='Lien affilié')),
                ('bonus_montant', models.CharField(blank=True, max_length=100, verbose_name='Montant du bonus')),
                ('bonus_type', models.CharField(choices=[('depot', 'Bonus sur dépôt'), ('sans_depot', 'Bonus sans dépôt'), ('freebets', 'Freebets')], default='depot', max_length=20, verbose_name='Type de bonus')),
                ('note', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='Note (/5)')),
                ('fiabilite', models.PositiveIntegerField(default=85, verbose_name='Fiabilité (%)')),
                ('disponible_benin', models.BooleanField(default=True, verbose_name='Disponible au Bénin')),
                ('accepte_mobile_money', models.BooleanField(default=True, verbose_name='Mobile Money')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bookmaker',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ClicAffilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clics', to='bookmakers.bookmaker')),
            ],
            options={
                'verbose_name': 'Clic affilié',
                'verbose_name_plural': 'Clics affiliés',
            },
        ),
    ]
